# Site settings
title:       Introduction to R in Ecology and Evolutionary Biology
email:       michaelalfaro@ucla.edu
author:      Michael Alfaro
description: "Materials for R bootcamp."
baseurl:     "/eeb201"
url:         "http://michaelalfaro.github.io/eeb201"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 

# Social icons
show_social_icons: true
github_username: michaelalfaro
stackoverflow_id:
twitter_username: tempoandmode
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'share'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown

#changing from redcarpet to kramdown markdown....
#https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
